@startuml
class ZeroIntelligenceAgent {
  + __init__()
  + kernelStarting()
  + kernelStopping()
  + wakeup()
  + updateEstimates()
  + placeOrder()
  + receiveMessage()
  + cancelOrders()
  + getWakeFrequency()
}
TradingAgent <|-- ZeroIntelligenceAgent
@enduml