@startuml
class POVExecutionAgent {
  + __init__()
  + processEndTime() : "Make end time of POV order sensible, i.e. if a time is given leave it alone; else, add 24 hours to start."
  + wakeup()
  + getWakeFrequency()
  + receiveMessage()
  + handleOrderAcceptance()
  + handleOrderExecution()
  + cancelOrders()
}
TradingAgent <|-- POVExecutionAgent
@enduml