@startuml
class ImpactAgent {
  + __init__()
  + wakeup()
  + receiveMessage()
  + placeLimitOrder()
  + computeRequiredPrice()
  + getLastTrade()
  + getCurrentSpread()
  + getWakeFrequency()
}
TradingAgent <|-- ImpactAgent
@enduml