@startuml
class QLearningAgent {
  + __init__()
  + kernelStopping()
  + wakeup()
  + placeOrder()
  + receiveMessage()
  + cancelOrders()
  + getWakeFrequency()
}
TradingAgent <|-- QLearningAgent
@enduml