@startuml
class TradingAgent {
  + __init__()
  + kernelStarting()
  + kernelStopping()
  + wakeup()
  + requestDataSubscription()
  + cancelDataSubscription()
  + receiveMessage()
  + getLastTrade()
  + getCurrentSpread()
  + getOrderStream()
  + get_transacted_volume()
  + placeLimitOrder()
  + placeMarketOrder()
  + cancelOrder()
  + modifyOrder()
  + orderExecuted()
  + orderAccepted()
  + orderCancelled()
  + marketClosed()
  + queryLastTrade()
  + querySpread()
  + handleMarketData()
  + queryOrderStream()
  + query_transacted_volume()
  + getKnownBidAsk()
  + getKnownLiquidity()
  + getBookLiquidity()
  + markToMarket()
  + getHoldings()
  + getKnownBidAskMidpoint()
  + get_average_transaction_price()
  + fmtHoldings()
}
FinancialAgent <|-- TradingAgent
@enduml