@startuml
class ValueAgent {
  + __init__()
  + kernelStarting()
  + kernelStopping()
  + wakeup()
  + updateEstimates()
  + placeOrder()
  + receiveMessage()
  + cancelOrders()
  + getWakeFrequency()
}
TradingAgent <|-- ValueAgent
@enduml