@startuml
class EtfPrimaryAgent {
  + __init__()
  + kernelStarting()
  + kernelStopping()
  + wakeup()
  + receiveMessage()
  + queryLastTrade()
  + getLastTrade()
  + getPrimeOpen()
  + getPrimeClose()
}
FinancialAgent <|-- EtfPrimaryAgent
@enduml