@startuml
class ExampleExperimentalAgent {
  + __init__()
  + getCurrentMidPrice()
  + receiveMessage()
  + computeMidPriceMovingAverages()
  + wakeup()
  + getWakeFrequency()
}
ExampleExperimentalAgentTemplate <|-- ExampleExperimentalAgent
@enduml