@startuml
class ExampleExperimentalAgentTemplate {
  + __init__()
  + wakeup()
  + receiveMessage()
  + getWakeFrequency()
  + placeLimitOrder()
  + placeMarketOrder()
  + cancelAllOrders()
}
SubscriptionAgent <|-- ExampleExperimentalAgentTemplate
@enduml