@startuml
class POVExecutionAgent {
  + __init__()
  + processEndTime()
  + wakeup()
  + getWakeFrequency()
  + receiveMessage()
  + handleOrderAcceptance()
  + handleOrderExecution()
  + cancelOrders()
}
TradingAgent <|-- POVExecutionAgent
@enduml