@startuml
class MarketMakerAgent {
  + __init__()
  + kernelStarting()
  + wakeup()
  + receiveMessage()
  + placeOrders()
  + cancelOrders()
  + getWakeFrequency()
}
TradingAgent <|-- MarketMakerAgent
@enduml